### ISSUE TITLE
We should announce a cut/copy/paste/delete event

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#182]
For screenreader users, we need spoken feedback for these events:

"deleted (+ 1 2)"
"cut (* 3 4)"
"copied (string-length "hello")"

**Comment by justinpombrio** [comment]
Literally that feedback, or should it give the verbose description given by `toDescription`, like `say: copied applying the function > to 2 arguments 1: x, 2: 0`?

**Comment by justinpombrio** [comment]
`options['aria-label']` looks more appropriate to me. It produces, e.g., `say: deleted + expression, 2 inputs`. Is that what we want for these messages?

**Comment by schanzer** [comment]
Yes

**Comment by justinpombrio** [comment]
This should be fixed by 997b50ef79fe51557. When nothing is selected, it says "Nothing selected", as before. When one or more things are cut, copied, or deleted at once, it joins them with "and". For example:

    say: deleted subtract expression, 2 inputs and 9

I see one further issue along this line: `copyNodes` in `actions.js` activates (one of) the node(s) that was just copied, and speaks it. This also fires during `cut`, which copies nodes before deleting them. So for `cut` and `copy`, one of the nodes is spoken twice. Should this call to `activate` just go away? Does it have a purpose besides speaking?

**Comment by schanzer** [comment]
Fixed in 7eaec945585ded13283cc1d7bf61cabf76603b8f
