### ISSUE TITLE
dispatchEvent not pressing keys

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#195]
The last two tests in `new-focus-tests` fail. (At the moment, you'll need to set these to run to reproduce this. Just change the test that's run in `spec/index.js` to `new-focus-test.js`.)

What's happening is that this line:

    document.dispatchEvent(keypress(48 + 9)); // the '9' key

should be simulating pressing the '9' key. But it isn't: while running the test case, the digit '9' doesn't appear. But as the test case is running, if _I_ press '9' then the digit '9' does appear. So it doesn't quite simulate a key press.

Unfortunately AFAIK none of our code is involved in any of this, so it's hard to debug.

**Comment by schanzer** [comment]
Is it possible that we _need_ to be dispatching the event on the element itself, rather than the whole document? That seems plausible to me, especially since the event needs to bubble up in order for React to...well...react. If we're dispatching on the `document`, React might never even see it. I'm thinking something along the lines of:

```
 this.cmb.cm.getWrapperElement().dispatchEvent(keypress(48 + 9)); // the '9' key
`this.cmb.cm.getWrapperElement().dispatchEvent(keypress(ENTER)); // save changes
```

...but the ENTER event needs to be dispatched on the quarantine node, not the wrapper. Not sure how to get that node in the current setup.

**Comment by schanzer** [comment]
Actually - it's more than that. The `NodeEditable` component listens for _keydown_ events, not keypresses. As a result, it's just ignoring the events Karma is firing. So to get things listening at all, we need:
`document.activeElement.dispatchEvent(keydown(48 + 9)); // the '9' key`

**Comment by schanzer** [comment]
Further study: karma doesn’t generate onInput() events, which our contentEditable component listens for.

**Comment by schanzer** [comment]
See https://github.com/bootstrapworld/codemirror-blocks/commit/8cb9f8f498f774c627b5aa3896a0c27a0ba49fb9

**Comment by schanzer** [comment]
@justinpombrio is this fixed, either due to `Simulate` or using my hack?

**Comment by justinpombrio** [comment]
Yes, thank you.
