### ISSUE TITLE
Bring back the trashcan

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#215]
Kbd shortcuts should not be required to delete a node

**Comment by justinpombrio** [comment]
Partially implemented by c620dcadcf86de0aef5a01bea9cf0255a24eabb1.

I'm going to leave things here, because the rest of the work will be done much faster by someone who knows anything about css:
- [x] Make a trash can that you can drop things into and they get deleted.
- [ ] Fix the fact that `onDragEnter` and `onDragLeave` fire both for the outer `div` and for the trashcan icon on the `div`. We want these to only fire once.
- [ ] Once that is fixed, the trash can will have an accurate `"over"` css class, that says whether you're currently dragging something over it. Add css to make it big and gobbley-looking when `over` is true.
- [ ] Make the trash can and the text beneath it not look terrible.
