### ISSUE TITLE
Dragging block to same location fails to re-render

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#225]
Start with this program:

    (after) #| after |#
    (none)

Enter block mode, and drag the `none` block to the right of the `after` block. What should happen is that the `none` block goes back exactly where it was before (as it can't go on the same line because of the comment).

Instead, what happens is that it goes back to the same line, but fails to re-render, showing instead as the *text* `(none)`.

I believe that the heuristics in `BlockComponent.shouldComponentUpdate` are saying "none of the props (such as location) have changed, so this block doesn't need to re-render!".

**Comment by schanzer** [comment]
The issue here is delicate interaction with the way we implement dragging: all dragging operations involve both clearing and re-painting, so the DOM node *is* being torn down. A re-render is in fact required, but right now we avoid that if all the props are the same. We need to add another condition, that triggers a redraw if the DOM node is no longer contained in the document.
