### ISSUE TITLE
Fail gracefully in case of parser error

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#241]
Right now, the whole editor becomes severely unstable if there's a parser error. We rely way too much on the language and language designer to be clever enough to fail gracefully. 

Instead, we need to `try/catch` here, throw up a dialog indicating that "this edit is not allowed", and cancel the edit.

**Comment by justinpombrio** [comment]
There is a `try/catch` block in `commitChanges` for this purpose. It correctly detects and logs errors, and calls its `onError` callback. This goes to (e.g.?) the `onError` callback (see `e => {`) in `NodeEditable.js`. Presumably what happens there is bad, because it seems to brick the editor, so that you need to reload the page for it to become responsive again.

**Comment by schanzer** [comment]
This is fixed by the inclusion of `NodeSpec`s, which landed with the `editing-syntax` branch
