### ISSUE TITLE
Possible Comparison Operator Syntax

### ISSUE THREAD

**Issue by MadeofTin** [bootstrapworld/codemirror-blocks#31]
Compiled a list of Comparison Operators with a possible unifying syntax. Am I missing or off base on any of these? @pcardune 

Equals
- [ ] =!= Not equal too
- [ ] =<= Less than or equal
- [ ] =>= Greater than or equal
- [ ] === Equivalent

Is
- [ ] _=_ is
- [ ] _!_ is not
- [ ] _>_ is greater than
- [ ] _<_ is less that

**Comment by MadeofTin** [comment]
Dang Markdown stripped the syntax of the Is operators. I'll make a visual version.

**Comment by MadeofTin** [comment]
A visual version of it. Personally I like the spacial consistency of the three characters per operator.
![Comparison Operators](https://docs.google.com/drawings/d/1xA01trnxbDIHDmFr_XmyD0GRvNkvoXDMgTK3EBGwe_Q/pub?w=300)

**Comment by shriram** [comment]
Sweet proposal to consider!

One thing to check is how these translate to textual languages, and whether they will cause any confusion if this is the syntax that students embed in their heads. This seems problematic in that regard.

I also find the _ vs = pretty confusing. In one case, the = is an actual part of the semantics. But in the other case, the _ is just part of the syntax. So underscore-equal-underscore reads like “this is a two-place operator, with things on the left and right”; whereas the = version does not.

Finally, I wonder why three-character consistency matters. These are the only characters the students will _not_ be writing, since they'll be dragging in blocks.

**Comment by MadeofTin** [comment]
The confusion is already a problem within textual contexts. `=` isn't the same `=` in math. In programming is the assignment operator. In math `=` is an operation that results in True or False. `4 = 2 + 2` in math would result in True. But in programming it is more like an arrow function. The value of `2 + 2` gets assigned to '4'. You could also do `5 = 2+2` and that would result in `5` being reassigned to be the result of expression `2+2`. Which then `5 = 4`?.

Python resolves this with the `==`, but then there is also the `is` keyword. Which both are of the same class of operator. The intention was to keep them visually similar to tie the idea that conceptually they are similar.

**Comment by MadeofTin** [comment]
The other option could be to have `=` be the same it is in math, but then you would need a different assignment operator. `➔` or `=>`, but then that has the same issue with consistency with textual programming languages.

**Comment by shriram** [comment]
`=` is not an assignment operator in the languages that this system is being designed for. These languages do not have assignment, period, or if they do it's with a drastically different syntax. So there is no “confusion” here.

**Comment by MadeofTin** [comment]
Then it makes sense. I still need to get my head wrapped around the differences to functional programming.

Does this resolve it?

![](https://docs.google.com/drawings/d/1DanqxTf76_HdnOlX4Eyc9zl0QQBPdruBZBZ6sY1_Mes/pub?w=300)

**Comment by shriram** [comment]
I have no idea why one would use `!` to mean “not equal”, as opposed to `≠`. I also don't understand what “is not” means (or, how it's different from “not equal to”).

Separately, my understanding was that @pcardune was making this to be a generic front-end, with different languages using it. If that's still the case, than it's most likely that the blocks would use operators that represent the syntax of the particular language they're layered atop, rather than have different, generic operators. (After all, the very set of operators depends on the underlying language.)

**Comment by MadeofTin** [comment]
To the first comment, you're right, I have no idea why I didn't think of `≠`. That is a much better option. I need to remember we are free from the keyboard. 

2nd, The "is not" may also not be used in functional languages. You can use it for checking data types and such. Maybe you could use it with structs in scheme. 

Pardon my python example code
```python
def not_an_int(x):
    if (x is not int):
        return True
    else:
        return False
```

It gets more useful when using classes and subclasses

```python
class Shape:
...

class Triangle(Shape):
...

class Square(Shape):
...
```
With this set up you can do one thing to Triangles and one thing to Squares.
Again may not be useful in scheme, so it may be better to leave out.

**Comment by MadeofTin** [comment]
For the last point regarding @pcardune, I could see it going either direction. You could have one unifying conceptual syntax that then you explain how different languages represent them. Or, you could have the syntax change depending on the language you are representing. Both have their points of confusion, but I am not sure which would be less confusing for students. @shriram is there one approach that seems like it would create less friction for the students learning?

**Comment by pcardune** [comment]
Just reading through all this now. Here are some high level thoughts.

This library *is* meant to be generic, both in terms of the underlying programming language that gets used, and in terms of the way that language gets rendered into visual blocks.

That said, I intend for this library to come with some "batteries included", both to serve as examples for future integrations and to make it more useful out of the box. That's why the wescheme parser and renderer is built in.

So the question I think we should be thinking about is which "batteries" we want to prioritize building. Here's a list of parsers/renderers that I think would be interesting/useful, in priority order:

P0: bootstrap flavor wescheme parser + renderer

This should be 100% oriented towards the bootstrap curriculum and the students that will be using it. I expect Emmanuel to have the strongest and most informed opinions about this and I'm happy for him to be the benevolent dictator with respect to how this should work. From what I've seen of the curriculum, and in talking to Emmanuel, this will likely be a fairly simplified subset of the features that this library will ultimately be capable of providing, and won't be suitable for writing serious programs outside the context of the bootstrap curriculum. This is the highest priority because bootstrap is our first and primary real world use case. If we don't get this part right, then we've failed.

P1: "advanced" scheme parser + renderer

This should be geared towards supporting all the features of scheme and be oriented towards advanced students who are well beyond what the bootstrap curriculum covers. For example, if you are a college student taking a functional programming class for which scheme is the language being used, you should be able to use the block editor to do your homework. I expect the rendering to look quite a bit different for this use case, since programs will be much more complex and longer. This is important because it serves as a forcing function to make the library truly feature complete and flexible enough to work for a large variety of use cases. It would also be super impressive and a good way to market towards professional software developers who are building developer tools. Basically we would prove that this library is not just a toy.

P2: super simple example language parser and renderer

This is really just documentation for how to get started writing your own parser/renderer. I don't expect anyone to actually use it except as a reference. It would be the minimum amount of code necessary to illustrate how the library works. This is important because documentation is important both for growing a community of users and for marketing.

P3: JavaScript parser + renderer

Basically the same story as P1 but for a language that is substantially more popular than scheme.

P4: experimental language parser / renderer

This would essentially be a testing ground for new ideas that could later be incorporated into other parsers/renderers. We would be trying to push the boundaries of what block languages/editors are capable of. 


So to the extent that we are making product decisions about how the library should or shouldn't work, we should make sure to know which of the above priorities we are talking about so we don't end up talking past each other or spinning our wheels on something that is not super important.

As for @madeoftin's proposal, I could see that fitting in with P4 or P2.

I'm on the road right now but perhaps we could have a real time discussion about this on gitter later today.

**Comment by shriram** [comment]
Thanks Paul. I'm happy to defer to @schanzer as the benevolent dictator too.

We are definitely interested in integrating this with Pyret (http://www.pyret.org/). Pyret's on-line IDE is built using CodeMirror, so hopefully there is a not-too-painful integration path. In addition, while we use Racket/Scheme for Bootstrap 1, we use Pyret for Bootstrap 2 onwards, so eventually there is an integration path there. Plus, there are others starting to use Pyret in introductory curricula, so a block-first interface could be attractive to them, too.

@MadeofTin, thanks for clarifying `is not`. I had a hunch you were alluding to the Python operator. That kind of nominal check is indeed useful in languages that have a notion of nominality, but the choice of operator name in Python is, I think, especially confusing or at least unintuitive. At any rate, it seems like a low priority for the block language, for the simple reason we are unlikely to use this language to introduce new datatypes (at that point you're beyond the point of the block language's design) — this is something @schanzer and I both believe — so there is relatively little use/need for nominal tests.

**Comment by schanzer** [comment]
The idea of a unifying conceptual syntax is certainly intriguing, and is precisely the kind of experiment this toolkit will make possible. I think we all agree that the toolkit should never _enforce_ such a syntax. That leaves us with @pcardune 's priority queue, which I heartily endorse -- a unifying syntax does not serve us well for Bootstrap, unless we're prepared to agree that Bootstrap's syntax is _the_ syntax. :)

@MadeofTin , your proposal sounds like a superb use-case for P4, which could be piloted as part of P2. Do you agree?

(I should also add that P1 would be great for Bootstrap -- P0 only covers the first two units of our 10-unit sequence)

**Comment by pcardune** [comment]
Going to close this since I think we answered the question.
