### ISSUE TITLE
Investigate Heisenbugs

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#391]
The test suite remains frustratingly brittle:

- [x] Of the [three tests](https://github.com/bootstrapworld/codemirror-blocks/blob/master/spec/comment-test.js) in `comment-test.js`, the 2nd or 3rd fails pretty reliably _even with a significant added delay_. My hunch is that `setQuarantine` is relying on state that isn't being reliably replicated in the tests.
- [x] Without [a short delay](https://github.com/bootstrapworld/codemirror-blocks/blob/master/src/toolkit/test-utils.ts#L31), most tests fail -- even though we're now [waiting for React to finish the render](https://github.com/bootstrapworld/codemirror-blocks/blob/master/src/toolkit/test-utils.ts#L29). This wait is used multiple times in nearly ever test, resulting in significantly longer test runs than may be necessary.
- [x] Roughly 50% of the time, one of the tests will fail with `TypeError: Cannot read property 'focus' of null`. Sourcemaps aren't propagating into Karma, so this makes debugging incredibly difficult. However, I'm fairly certain it's one of the tests in [activation-test.js](https://github.com/bootstrapworld/codemirror-blocks/blob/master/spec/activation-test.js), since that stress tests all kinds of codepaths that result in `someNodeX.focus()` being called inside [activateByNid](https://github.com/bootstrapworld/codemirror-blocks/blob/master/src/actions.ts#L173-L252). HUNCH: since that code relies on setTimeout to let the DOM and/or CM update, we're breaking out of React's render cycle. What we actually need is for this function to be called via `editor.afterDOMUpdate()` rather than inside a timeout*. 

*I don't know how to implement this, since it feels like the right way to do it is to use React Contexts to expose that method across the editor and I'm just not comfortable enough with Contexts to do it. There are quite a few places where we could make better use of Contexts, and this is yet another reason for me to learn how they work.

**Comment by pcardune** [comment]
So I did a bit of investigating and I think the reason why the focus error comes up is because of our use of `setTimeout()`. Here's the error:

```
  An error was thrown in afterAll
  TypeError: Cannot read property 'focus' of null
      at webpack://codemirror-blocks/src/actions.ts:199:53 <- activation-test.1875702655.js:77858:59
      at webpack://codemirror-blocks/node_modules/redux-thunk/es/index.js:8:18 <- activation-test.1875702655.js:59761:18
      at Object.activateByNid (webpack://codemirror-blocks/src/ui/BlockEditor.tsx:208:64 <- activation-test.1875702655.js:82377:33)
      at webpack://codemirror-blocks/src/ui/BlockEditor.tsx:646:37 <- activation-test.1875702655.js:82517:49
```

Here's the flow in activation-test:

1. `cmb.setValue()` this updates the text in codemirror, which triggers a 'cursorActivity' event
2. `BlockEditor.handleTopLevelCursorActivity` captures this event and dispatches a `setCursor()` action to redux
3. the `setCursor` action calls `cm.focus()` on the codemirror instance, which triggers a 'focus' event
4. `BlockEditor.handleTopLevelFocus` captures this event, which triggers a setTimeout to be executed later
5. react renders everything according to the current state.

6. now the setTimeout callback executes, which calls activateByNid, which in turn _might_ look for an element:

    ```ts
    // If the element has been ellided by CM, it won't be in the DOM. This
    // can lead to situations where CM ellides the *currently-focused* elt,
    // which confuses the screenreader. In these situations, we focus on
    // a dummy element that just says "stand by" (see ToggleEditor.js).
    // When the new node is available, focus will shift automatically.
    if(!document.contains(newNode.element)) {
      document.getElementById('SR_fix_for_slow_dom').focus();
    }
    ```

The node its looking for gets rendered by ToggleEditor, but there's nothing that really guarantees that the node still exists in the dom. So why might the node no longer exist in the dom? Well...

The error is happening in `afterAll`, which is after all the tests have run. Inside activation-test we have:

```ts
afterEach(function () { teardown(); });
```

`teardown()` is from our test-utils, and it calls `cleanup()` from `@testing-library/react` which unmounts all the react trees... removing them from the DOM.

So there is a race condition between a test finishing and the `setTimeout` callback being executed. If a test finishes first, we get this error.

Most of the time we prevent the test from finishing first by calling `await finishRender()` after anything that might trigger `BlockEditor.handleTopLevelFocus`, but there are some tests that don't do this, like the ones in "tree navigation" which call `keyDown()` without a corresponding `await finishRender()`.

**How To Fix**

I think these are the options:
1. change `activateByNid` to check if 'SR_fix_for_slow_dom' still exists before trying to call focus on it. If we were to turn on `strictNullChecks` in typescript, it would complain about this. This error is the same as having a dangling pointer.
2. change `BlockEditor.handleTopLevelFocus` to keep track of the timeout somewhere and cancel it in `componentWillUnmount`. The new react hooks api handles this sort of automatic cleanup very nicely with [the useEffect hook](https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup).
3. both of the above

Option 1 is quick and dirty and will make the focus problem go away.

Option 2 enforces the proper semantics for the code, but requires more effort to do the bookkeeping correctly. In general it's never ok to call a setTimeout() from inside a react component without having something to cancel the timeout on unmount. It would be best to fix all of them (I counted 11 in the code base).  This is really easy with `useEffect`, but we can't use react hooks inside of class components, so that would require converting the class components to functional components which is an even bigger task.

I'm going to submit a PR for option 1, and create a new issue for option 2.

**Comment by pcardune** [comment]
There's also an option 4, which I'm not sure exactly how to do properly, but involves sharing a reference to the 'SR_fix_for_slow_dom' node between ToggleEditor and activateByNid in a way that ensures there is no dangling pointer.
