### ISSUE TITLE
Make this a proper CodeMirror extension

### ISSUE THREAD

**Issue by pcardune** [bootstrapworld/codemirror-blocks#66]
See http://codemirror.net/doc/manual.html#defineExtension

Expose a `setBlockMode(Boolean)` method on the CodeMirror object that turns block rendering on/off

**Comment by justinpombrio** [comment]
@schanzer It looks like you did this with
c9e1f7ce58ead23631700484d92e89dcb0572395, with the method named `external.handleToggle(Boolean)`?

**Comment by schanzer** [comment]
Not quite. CM its own notion of “extensions“, and at one time it seemed like a great goal to have this be one of them.  I’m not convinced that makes sense anymore, especially since they are moving to a new architecture in version 6 anyway, so any effort but towards this issue would have to be duplicated next year
